Requirements
============

* Make sure Python2.7 with setuptools is installed

Introduction
============

Setup environment
-----------------

#. git clone git://github.com/jstasiak/rznij.git
#. easy_install pip
#. pip install virtualenv
#. cd rznij
#. virtualenv .
#. source bin/activate
#. pip install -r pip_requirements.txt

Configuration
-------------

#. Fill local_settings.py (template in local_settings.py.template), set SERVER_ADDRESS as needed
#. Do manage.py collectstatic and manage.py syncdb

Running
-------

`python manage.py rungevent 0:8000`

This will run server which will be listening on all your network interfaces on port 8000.


Notes
=====


* Application has to be run by manage.py rungevent because of gevent monkey patching and running gevent-socketio server instead of Django development server
* Currently website is in Polish, translation in progress ;)
* shared static files are in static_common directory, all static files have to be collected by manage.py collectstatic command
* development version (hg/develop branch) of gevent-socketio (https://github.com/jstasiak/gevent-socketio) is required, pip_requirements.txt should take care of this


Author
======

Jakub Stasiak <kuba.stasiak at gmail.com>
