
How to run
==========

# Make sure that requirements are installed:

 * gevent >= 0.13.4
 * Python 2.x >= 2.7
# download code (clone with --recursive option to download submodule(s) too)
# Copy local_settings.py.template to local_settings.py and change variables as needed
# manage.py collectstatic
# manage.py syncdb
# run.py

Notes
=====


* latest gevent-websocket included in libraries directory
* remember to pull submodule gevent-socketio when cloning or manually later (!). This project will work only with this specific version of gevent-socketio
* Application has to be run by run.py script because of gevent monkey patching and running gevent-socketio server instead of Django development server
* Currently website is in Polish, translation in progress ;)
* shared static files are in static_common directory, all static files have to be collected by manage.py collectstatic command
* remember to fill local_settings.py file (template in local_settings.py.template file)


Author
======

Jakub Stasiak <kuba.stasiak at gmail.com>
